name: Azure CLI with git clone Tests
on: 
  push:
      branches:
        - main
  
  workflow_dispatch:
  
jobs:
  Login-Azure:
    runs-on: self-hosted
    steps:            
    - name: "Login to Azure"
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: "Login and do something"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.24.2
        inlineScript: |
          az login --identity
          az vm run-command invoke \
          -g myResourceGroup \
          -n myVM \
          --command-id RunShellScript \
          --scripts "sudo apt-get update && cd /var/www/html/gamify && pwd && ls -lah"
